---
services:
  pilot:
    git_url: https://github.com/DimitriosLisenko/pilot.git
    git_branch: multiple-dockerfiles-no-dockerfile
    ports:
    - container: 8050
      http: 80
      https: 443
    command: "/go/src/app/app --port=8050 --dport=8051 --dip=zigot._env(NAMESPACE)"
  zigot:
    git_url: https://github.com/DimitriosLisenko/pilot.git
    git_branch: multiple-dockerfiles-no-dockerfile
    ports:
    - container: 8051
    command: "/go/src/app/app --port=8051 --dport=8050 --dip=pilot._env(NAMESPACE)"
